### PR TITLE
982 fix order columns

### LINKED ISSUE #971: Setting column order is not implemented
The CrudPanel `setColumnOrder` method in the Columns trait is exposed in the public API but is not implemented.

There is also an `orderColumns` method in the same trait (which also does not work).

@tabacitu, my proposal would be to just remove the `setColumnOrder` method and then fix the `orderColumns` method.

### LINKED ISSUE #982: Ordering columns does not work
The CrudPanel `orderColumns` method in the Columns trait does not order the columns.

### PR DESCRIPTION
**Pull request by tumf87**
Fixes #982.
Fixes #971.

@tabacitu, please notice that, as part of this PR, I've deprecated the unimplemented `setColumnOrder` and `setColumnsOrder`.

I've also noitced that the `addColumn` method ended with a `return $this` statement (the `$crudPanel`), which was odd, undocumented and different from the `addColumns` method, so I decided to remove it.

I know this is a breaking change and I can revert it if you like, but IMHO I think we should just go with it.

### CODE REVIEW

File: src/PanelTraits/Columns.php [hunk 1]
```diff
@@ -263,18 +254,52 @@ public function getColumnsRelationships()
...
+        $remaining = array_diff_key($this->columns, $orderedColumns);
+        $this->columns = array_merge($orderedColumns, $remaining);
+    }
+
+    /**
+     * Set the order of the CRUD columns.
+     *
+     * @param array $columns Column order.
+     *
+     * @deprecated This method was not and will not be implemented since its a duplicate of the orderColumns method.
```
Comment (lloy0076) [inline src/PanelTraits/Columns.php]: it's (or) its but **not** "its [sic]".

File: src/PanelTraits/Columns.php [hunk 2]
```diff
@@ -263,18 +254,52 @@ public function getColumnsRelationships()
         })->toArray();
     }
 
-    // ------------
-    // TONE FUNCTIONS - UNDOCUMENTED, UNTESTED, SOME MAY BE USED
-    // ------------
-    // TODO: check them
+    /**
+     * Order the CRUD columns. If certain columns are missing from the given order array, they will be pushed to the
```
Comment (lloy0076) [inline src/PanelTraits/Columns.php]: That second sentence probably should be in the function description.

File: src/PanelTraits/Columns.php [hunk 3]
```diff
@@ -263,18 +254,52 @@ public function getColumnsRelationships()
...
+     * new columns array in the original order.
+     *
+     * @param array $order An array of column names in the desired order.
+     */
+    public function orderColumns($order)
```
Comment (lloy0076) [inline src/PanelTraits/Columns.php]: Is this really ordering the columns?

To me, "ordering the columns" sounds like "sorting the columns".

If one wanted to do a German-like add words together this sounds like "putTheColumnsInTheSpecifiedOrder" or "orderColumnsAsSpecified" but those names are horrid.

In **fact** this almost sounds like `setColumnOrder` or something.

Comment (tumf87) [reply src/PanelTraits/Columns.php]: @lloy0076, I agree, but we need to keep the method name for backwards compatibility...

**Comment by tumf87** [comment]
@tabacitu, I've noticed some people were adding columns with this syntax:

`$this->crudPanel->addField($field1)->addField($field2)`

which is why the method was returning `$this`.

That's a weird mix of a method and a builder pattern and we should consider refactoring it in the future.
Since obviously people are using the method this way, I will revert the change for backwards compatibility.

**Comment by tabacitu** [comment]
Thank you @tumf87 ! Merged on dev!
