### PR TITLE
Fixes #1542

### LINKED ISSUE #1542: Validation rules as array cause Exception
# Bug report

### What I did:
Defined request rules as array (to make use of [closures](https://laravel.com/docs/5.6/validation#using-closures) or [custom rule objects](https://laravel.com/docs/5.6/validation#custom-validation-rules)) as described in the Laravel docs.
Example from any Request class:
```php
...
    public function rules()
    {
        return [
            'name' => [
                'required',
                'min:5',
                'max:255',
            ]
        ];
    }
...
```

### What I expected to happen:
Working validation of array rule set.

### What happened:
ErrorException:
`ErrorException(code: 0): strpos() expects parameter 1 to be string, array given at .../vendor/backpack/crud/src/PanelTraits/RequiredFields.php:30)`
The problem is not usage of closures or rule objects, but to define a rule set as array, rather than pipe separated string.

### What I've already tried to fix it:
Really simple fix in trait `RequiredFields` incoming via PR.

The only currently working workaround I figured out, is to write a second version of each request, in which `rules()` returns a rule set only containing `required` rules on required inputs. This second request can then be passed to `$this->crud->setRequiredFields()` while `create()` and `update()` hint the original request classes. Among workarounds, this is one of the worst :smile: 

### Backpack, Laravel, PHP, DB version:
backpack/base                         0.9.6
backpack/crud                         3.4.23
mysql                                       5.7.22
PHP                                         7.2.7

### PR DESCRIPTION
**Pull request by mark-win**
To fix #1542 I enhanced `RequiredFields::setRequiredFields()` to accept rule sets defined as array, rather than pipe separated string.

### CODE REVIEW

File: src/PanelTraits/RequiredFields.php [hunk 1]
```diff
@@ -26,7 +26,10 @@ public function setRequiredFields($class, $operation)
 
         if (count($rules)) {
             foreach ($rules as $key => $rule) {
-                if (strpos($rule, 'required') !== false) {
+                if (
```
Comment (lloy0076) [inline src/PanelTraits/RequiredFields.php]: https://secure.php.net/manual/en/function.strpos.php

```

Return Values ¶

Returns the position of where the needle exists relative to the beginning of the haystack string (independent of offset). Also note that string positions start at 0, and not 1.

Returns FALSE if the needle was not found.
Warning

This function may return Boolean FALSE, but may also return a non-Boolean value which evaluates to FALSE. Please read the section on Booleans for more information. Use the === operator for testing the return value of this function.
```

Comment (mark-win) [reply src/PanelTraits/RequiredFields.php]: Thanks for the feedback. Please note, that we want to evaluate, that array_search does find the string 'required' in the array. So the supposed return value is anything unequal false. You are right, that we need to perform a type sensitive comparison. That is why I used `!==` instead of a simple `!=`.
In other words: we need the inverse of `===`. And that would be `!==`, which is what I did in my first commit.

Please correct me, if i got your feedback wrong. I respond from my mobile and might have missed a thing.

Comment (tabacitu) [reply src/PanelTraits/RequiredFields.php]: Totally agree with you here @mark-win ! I think ```!==``` will do just fine.

**Comment by tabacitu** [comment]
Thanks a lot for reporting the issue, AND fixing it @mark-win ! That does NOT happen every day, so again - thank you :-)

The PR looks perfect to me, no comments. Just merged it, so it'll be available to you and everyone else after a ```composer update```.

Keep 'em coming :-)
Cheers!
