### PR TITLE
[4.1][FIX] FetchOperation error with multiple search attributes - add fetch single

### LINKED ISSUE #2704: [4.1] Fetch search multiple attributes, doc identifiable attribute
# Bug report

### What I did

Searched a relationship field in the Create screen

### What I expected to happen

Entities for the targeted model to be listed in the Select2 field

### What happened

SQL query failed. Without explicitly defining the 'identifiableAttribute' on the target Model, the CRUD field definition is ignored. In my case, created_at was used to search, possibly because it was the first column in the table.

### What I've already tried to fix it

Declared identifiableAttribute on the target Model. Cannot overwrite the searched column by passing a value to the CRUD field definition.

### Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

### PHP VERSION:
PHP 7.3.11-0ubuntu0.19.10.4 (cli) (built: Apr  8 2020 18:58:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-0ubuntu0.19.10.4, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
v7.7.1@4de129177f889cd7672e732d8808020adfb7b121

### BACKPACK VERSION:
4.1.x-dev@78a89604e4d8571671bb9ec6f2d626a1e8150078

### Field Definition ###

$this->crud->addField([
            'type' => 'relationship',
            'attribute' => 'Common_Name',
            'entity' => 'species',
            'name' => 'species',
            'model' => 'App\Models\Plant\Species',
            'label' => 'Species',
            'placeholder' => 'Select Species',
            'ajax' => true,
            'incline_create' => true,
            'include_all_form_fields' => false
        ]);

### AJAX Response ###

"SQLSTATE[HY000]: General error: 1525 Incorrect TIMESTAMP value: 'Amer' (SQL: select count(*) as aggregate from `Species` where `created_at` = Amer)"

### PR DESCRIPTION
**Pull request by pxpm**
When we start building our query `$model->where()` or `$model->orWhere()` we no longer have a Model instance, we have a `Builder`, so our function `getColumnType()` to no longer works as it belongs to the model, and not to the builder. 

Also added the complete array of text columns, please @tabacitu when merging #2632 discard the changes in `FetchOperation.php`, the changes in this PR must prevail.

This also adds support to fetching a single entry. 

This fixes #2704 

I will also send the PR to the docs to fix the documentation part.

### CODE REVIEW

File: src/app/Http/Controllers/Operations/FetchOperation.php [hunk 1]
```diff
@@ -22,7 +22,7 @@ protected function setupFetchOperationRoutes($segment, $routeName, $controller)
 
         if (count($matches[1])) {
             foreach ($matches[1] as $methodName) {
-                Route::post($segment.'/fetch/'.Str::kebab($methodName), [
+                Route::post($segment.'/fetch/'.Str::kebab($methodName).'/{single?}', [
```
Comment (tabacitu) [inline src/app/Http/Controllers/Operations/FetchOperation.php:25]: I'd name this parameter ```key``` rather than ```single```:
- ```single```- implies a boolean to me
- ```key``` - implies an ID to me

File: src/app/Http/Controllers/Operations/FetchOperation.php [hunk 2]
```diff
@@ -70,11 +70,24 @@ private function fetch($arg)
...
         }
 
-        $textColumnTypes = ['string', 'json_string', 'text'];
+        // FetchOperation has an optional parameter in url that when present means we want to fetch a single entity.
+        $fetchUriCount = count(explode('/', request()->route()->uri())) - 1;
+        $currentUriCount = count(explode('/', request()->path()));
+
+        //in this case last parameter in url was specified so we will trigger the return of single entity
+        if ($currentUriCount > $fetchUriCount) {
+            return $model_instance->where($model_instance->getKeyName(), $search_string)->first();
```
Comment (tabacitu) [inline src/app/Http/Controllers/Operations/FetchOperation.php:79]: Oh I see now. We're using the ```$search_string``` to pass the ID from select2 to the Fetch operation. I understand now. 

Any reason why we don't use the new parameter to pass the exact ID? Then we could just check if the parameter exists - and if so, it's the ID.

Comment (pxpm) [reply src/app/Http/Controllers/Operations/FetchOperation.php:79]: I did it this way because I am not 100% sure how it will work for multiple selects (I think the same) but the query string would be a json string representation of an array of id's.

That's why i used the parameter, as you said correctly, as a boolean switch.

We could use the parameter as ID, but we only register one post route and would endup POSTING empty form to emulate a get request.

This way seemed more intuitive to me. For multiple i think i just have to try to `json_decode` the `search_string` if we have an array `return $model->whereIn('key', [array, of, ids])`

Comment (tabacitu) [reply src/app/Http/Controllers/Operations/FetchOperation.php:79]: Oh I understand. I agree with you then, it would be cleaner to use POST variables when send multiple IDs. It would work with GET too, but it'll be messy, especially if the IDs are actually UUIDs or something.

Then the best way to do this might be to:
- remove this new parameter entirely
- in the AJAX request, in addition to using the "q" parameter, we could also send a "keys" parameter (as POST variables, not GET)
- then inside the Fetch operation, we can just check to see if ```request()->has('keys')``` or ```count(request('keys'))```, and if so make sure to apply the proper logic

I think this would:
- leave the route simple and pretty, no ```/single``` flag; it would also require no parameter counting logic or anything;
- use POST instead of GET, to account for sending multiple IDs;

What do you think @pxpm ? Sounds good?

**Comment by tabacitu** [comment]
Looks perfect now. Good job @pxpm !
